version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .
    depends_on:
      - db

  # db is is db folder
  db:
    build: db/world-db/.
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: group18
      MYSQL_DATABASE: world
    ports:
      - "33060:3306"
    volumes:
      - ./world_db/world.sql:/docker-entrypoint-init db/world.sql