services:
  app:
    build: .
    container_name: app

  world-db:
    build: src/main/java/sql/world-db/.
    container_name: world-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33060:3306"