version: '3'

services:
  app:
    build: .
    container_name: app
    depends_on:
      - world-db

  world-db:
    build: src/main/sql/world-db/.
    container_name: world-db
    command: --default-authentication-plugin=group18
    restart: always
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: group18
      MYSQL_DATABASE: world  # This will create the 'world' database on startup
